[package]
name = "tangential"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.25.0"

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "./latex/docs-header.html"]
